### ISSUE TITLE
Issue when creating production build

### ISSUE THREAD

**Issue by dortega3000** [gadicc/meteor-react-hotloader#15]
When running the build in our CI server with the command:

sudo /usr/local/bin/meteor build ./build --directory

We get the following error:

[gadicc:hot] Failed to connect to your Mongo database on "mongodb://localhost:3001/meteor". Try MONGO_URL environment variable or "-p PORT" when running Meteor.
    
    /home/travis/.meteor/packages/gadicc_ecmascript-hot/.0.0.13-rc.10.okat4h++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/mongodb/lib/server.js:236
            process.nextTick(function() { throw err; })
                                                ^
    Error: MongoError: connect ECONNREFUSED
        at packages/gadicc_babel-compiler-hot.js:147:11
        at /home/travis/.meteor/packages/gadicc_ecmascript-hot/.0.0.13-rc.10.okat4h++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/mongodb/lib/mongo_client.js:276:20
        at /home/travis/.meteor/packages/gadicc_ecmascript-hot/.0.0.13-rc.10.okat4h++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/mongodb/lib/db.js:224:14
        at [object Object].<anonymous> (/home/travis/.meteor/packages/gadicc_ecmascript-hot/.0.0.13-rc.10.okat4h++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/mongodb/lib/server.js:234:9)
        at [object Object].g (events.js:180:16)
        at [object Object].emit (events.js:98:17)
        at [object Object].<anonymous> (/home/travis/.meteor/packages/gadicc_ecmascript-hot/.0.0.13-rc.10.okat4h++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:269:68)
        at [object Object].g (events.js:180:16)
        at [object Object].emit (events.js:98:17)
        at [object Object].<anonymous> (/home/travis/.meteor/packages/gadicc_ecmascript-hot/.0.0.13-rc.10.okat4h++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:81:12)
        at [object Object].g (events.js:180:16)
        at [object Object].emit (events.js:98:17)
        at Socket.<anonymous> (/home/travis/.meteor/packages/gadicc_ecmascript-hot/.0.0.13-rc.10.okat4h++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:124:49)
        at Socket.g (events.js:180:16)
        at Socket.emit (events.js:95:17)
        at net.js:441:14
        at process._tickCallback (node.js:458:13)
    FAILED: sudo /usr/local/bin/meteor build ./build --directory

**Comment by gadicc** [comment]
Hey, can you try `v0.0.14-rc.12` and confirm if it fixes this issue?  (ref https://github.com/gadicc/meteor-react-hotloader/commit/866ac20ae60d9bf45a3a6d71e448f390107aebe8)

P.S.  Have to ask, why are you running meteor build as root? :)

**Comment by gadicc** [comment]
Just doing some clean up, if this is still an issue, please re-open.  There was also a more recent change which solved this error in more obscure environments (e.g. cloud9 ide).
