### ISSUE TITLE
strange "Couldn't find preset "es2015"" error

### ISSUE THREAD

**Issue by ChrisOHu** [gadicc/meteor-react-hotloader#24]
Hi @gadicc ,

Really awesome work there : )

But when using this package following the instructions, I had this very strange error as pasted below.

best wisesh : )

```
=> Starting gadicc:ecmascript-hot server on port 3002.

=> Errors prevented startup:

   While processing files with gadicc:ecmascript-hot (for target web.browser):

   /Users/chrishu/.meteor/packages/gadicc_ecmascript-hot/.1.3.0_5.j6cxjm++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:372:17:
   Couldn't find preset "es2015" relative to directory "/Users/chrishu/Projects/IncV2/upweb"
   at
   /Users/chrishu/.meteor/packages/gadicc_ecmascript-hot/.1.3.0_5.j6cxjm++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:372:17
   at Array.map (native)
   at OptionManager.resolvePresets
   (/Users/chrishu/.meteor/packages/gadicc_ecmascript-hot/.1.3.0_5.j6cxjm++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
   at OptionManager.mergePresets
   (/Users/chrishu/.meteor/packages/gadicc_ecmascript-hot/.1.3.0_5.j6cxjm++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
   at OptionManager.mergeOptions
   (/Users/chrishu/.meteor/packages/gadicc_ecmascript-hot/.1.3.0_5.j6cxjm++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
   at OptionManager.addConfig
   (/Users/chrishu/.meteor/packages/gadicc_ecmascript-hot/.1.3.0_5.j6cxjm++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:207:10)
   at OptionManager.mergeOptions
   (/Users/chrishu/.meteor/packages/gadicc_ecmascript-hot/.1.3.0_5.j6cxjm++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:284:14)
   at OptionManager.addConfig
   (/Users/chrishu/.meteor/packages/gadicc_ecmascript-hot/.1.3.0_5.j6cxjm++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:207:10)
   at OptionManager.mergeOptions
   (/Users/chrishu/.meteor/packages/gadicc_ecmascript-hot/.1.3.0_5.j6cxjm++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:284:14)
   at OptionManager.init
   (/Users/chrishu/.meteor/packages/gadicc_ecmascript-hot/.1.3.0_5.j6cxjm++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:465:10)
   at File.initOptions
   (/Users/chrishu/.meteor/packages/gadicc_ecmascript-hot/.1.3.0_5.j6cxjm++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:194:75)
   at new File
   (/Users/chrishu/.meteor/packages/gadicc_ecmascript-hot/.1.3.0_5.j6cxjm++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:123:22)
   at Pipeline.transformFromAst
   (/Users/chrishu/.meteor/packages/gadicc_ecmascript-hot/.1.3.0_5.j6cxjm++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/pipeline.js:67:16)
   at
   /Users/chrishu/.meteor/packages/gadicc_ecmascript-hot/.1.3.0_5.j6cxjm++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/index.js:53:34
   at Cache.Cp.get
   (/Users/chrishu/.meteor/packages/gadicc_ecmascript-hot/.1.3.0_5.j6cxjm++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/cache.js:94:19)
   at Object.compile
   (/Users/chrishu/.meteor/packages/gadicc_ecmascript-hot/.1.3.0_5.j6cxjm++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/index.js:43:23)
   at Object.Babel.compile (packages/gadicc_babel-compiler-hot.js:447:24)
   at packages/gadicc_babel-compiler-hot.js:543:24
   at Function.time (/tools/tool-env/profile.js:305:10)
   at profile (packages/gadicc_babel-compiler-hot.js:604:20)
   at packages/gadicc_babel-compiler-hot.js:542:22
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget (packages/gadicc_babel-compiler-hot.js:491:14)

```

**Comment by gadicc** [comment]
Hey, it sounds like you have (at least)

```json
{
  "presets": [ "es2015" ]
}
```

but haven't

```sh
$ npm install --save-dev babel-preset-es2015
```

in your project?

If that's not it please paste your full `.babelrc` and directory listing of `node_modules`.

**Comment by ChrisOHu** [comment]
once I installed the missing babel-preset-* packages, this issue is resolved : )

**Comment by gadicc** [comment]
Great stuff :)
