### ISSUE TITLE
Couldn't resolve extends clause of ../.babelrc AND Couldn't find preset "meteor" relative to directory "/home/mordrax/code/cotwmtor"

### ISSUE THREAD

**Issue by mordrax** [gadicc/meteor-react-hotloader#28]
Update:
I also tried the latest package:
`gadicc:ecmascript-hot@1.3.0_5`
and I'm running meteor 1.3.1 but still getting the errors below.

Original:
I just tried toggling my packages today to this:
```
#ecmascript
gadicc:ecmascript-hot
```

And came across two issues (I think same root cause):

Running the `meteor` command in the root folder threw this:
`Couldn't find preset "meteor" relative to directory "/home/mordrax/code/cotwmtor"`

The full meteor error is something like this:
```
Changes to your project's package version selections:
                                              
gadicc:babel-compiler-hot   added, version 6.6.1_1
gadicc:ecmascript-hot       added, version 1.3.1_1
gadicc:hot                  added, version 0.0.15
gadicc:json5+               added, version 0.5.0-0
gadicc:modules-runtime-hot  added, version 0.6.2_2
meteorhacks:inject-initial  added, version 1.0.4

                                              
+ In order to resolve constraints, we had to use experimental versions of these
packages.
Creating /home/mordrax/code/cotwmtor/.babelrc\
Creating /home/mordrax/code/cotwmtor/client/.babelrc
=> Starting gadicc:ecmascript-hot server on port 3002.

=> Errors prevented startup:                  
   
   While processing files with gadicc:ecmascript-hot (for target web.browser):

   /home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:372:17:
   Couldn't find preset "meteor" relative to directory "/home/mordrax/code/cotwmtor"
   at
   /home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:372:17
   at Array.map (native)
   at OptionManager.resolvePresets
   (/home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
   at OptionManager.mergePresets
   (/home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
   at OptionManager.mergeOptions
   (/home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
   at OptionManager.addConfig
   (/home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:207:10)
   at OptionManager.mergeOptions
   (/home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:284:14)
   at OptionManager.addConfig
   (/home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:207:10)
   at OptionManager.mergeOptions
   (/home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:284:14)
   at OptionManager.init
   (/home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:465:10)
   at File.initOptions
   (/home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:194:75)
   at new File
   (/home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:123:22)
   at Pipeline.transformFromAst
   (/home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/pipeline.js:67:16)
   at /home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/index.js:53:34
   at Cache.Cp.get
   (/home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/cache.js:94:19)
   at Object.compile
   (/home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/index.js:43:23)
   at Object.Babel.compile (packages/gadicc_babel-compiler-hot.js:447:24)
   at packages/gadicc_babel-compiler-hot.js:543:24
   at Function.time (/tools/tool-env/profile.js:305:10)
   at profile (packages/gadicc_babel-compiler-hot.js:604:20)
   at packages/gadicc_babel-compiler-hot.js:542:22
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget (packages/gadicc_babel-compiler-hot.js:491:14)
   
   
   While processing files with gadicc:ecmascript-hot (for target os.linux.x86_64):

   /home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:372:17:
   Couldn't find preset "meteor" relative to directory "/home/mordrax/code/cotwmtor"
   at
   /home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:372:17
   at Array.map (native)
   at OptionManager.resolvePresets
   (/home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
   at OptionManager.mergePresets
   (/home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
   at OptionManager.mergeOptions
   (/home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
   at OptionManager.addConfig
   (/home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:207:10)
   at OptionManager.mergeOptions
   (/home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:284:14)
   at OptionManager.init
   (/home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:465:10)
   at File.initOptions
   (/home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:194:75)
   at new File
   (/home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:123:22)
   at Pipeline.transformFromAst
   (/home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/pipeline.js:67:16)
   at /home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/index.js:53:34
   at Cache.Cp.get
   (/home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/cache.js:94:19)
   at Object.compile
   (/home/mordrax/.meteor/packages/gadicc_ecmascript-hot/.1.3.1_1.7nrcqi++os+web.browser+web.cordova/plugin.compile-ecmascript-hot.os/npm/node_modules/meteor/gadicc_babel-compiler-hot/node_modules/meteor-babel/index.js:43:23)
   at Object.Babel.compile (packages/gadicc_babel-compiler-hot.js:447:24)
   at packages/gadicc_babel-compiler-hot.js:543:24
   at Function.time (/tools/tool-env/profile.js:305:10)
   at profile (packages/gadicc_babel-compiler-hot.js:604:20)
   at packages/gadicc_babel-compiler-hot.js:542:22
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget (packages/gadicc_babel-compiler-hot.js:491:14)
```

My tests (karma, webpack) in the `tests` folder threw this:
`Couldn't resolve extends clause of ../.babelrc in /home/mordrax/code/cotwmtor/client/.babelrc`

Full error (threw one of these for each file)
```
ERROR in ../client/reducers/areaReducer.js
Module build failed: Error: [BABEL] /home/mordrax/code/cotwmtor/client/reducers/areaReducer.js: Couldn't resolve extends clause of ../.babelrc in /home/mordrax/code/cotwmtor/client/.babelrc
    at Logger.error (/home/mordrax/code/cotwmtor/node_modules/babel-core/lib/transformation/file/logger.js:39:11)
    at OptionManager.mergeOptions (/home/mordrax/code/cotwmtor/node_modules/babel-core/lib/transformation/file/options/option-manager.js:286:32)
    at OptionManager.addConfig (/home/mordrax/code/cotwmtor/node_modules/babel-core/lib/transformation/file/options/option-manager.js:207:10)
    at OptionManager.findConfigs (/home/mordrax/code/cotwmtor/node_modules/babel-core/lib/transformation/file/options/option-manager.js:413:16)
    at OptionManager.init (/home/mordrax/code/cotwmtor/node_modules/babel-core/lib/transformation/file/options/option-manager.js:461:12)
    at File.initOptions (/home/mordrax/code/cotwmtor/node_modules/babel-core/lib/transformation/file/index.js:194:75)
    at new File (/home/mordrax/code/cotwmtor/node_modules/babel-core/lib/transformation/file/index.js:123:22)
    at Pipeline.transform (/home/mordrax/code/cotwmtor/node_modules/babel-core/lib/transformation/pipeline.js:45:16)
    at transpile (/home/mordrax/code/cotwmtor/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/home/mordrax/code/cotwmtor/node_modules/babel-loader/index.js:88:12)
 @ ./reducers/areasTest.js 7:19-66
```

**Comment by gadicc** [comment]
hey @mordrax!

The one you were using before `1.3.1_1` is actually the latest stable, I guess I need to update the thread.

Did you try `npm install --save-dev babel-preset-meteor` in your project root?  This was a new requirement in later versions, it's mentioned in the README and History but maybe you missed it.

For the "couldn't resolve" error, am I correct that that's outside of Meteor and just in your karma/webpack tests?  I'd like to stay compatible with these but the "extends" clause is a pure babel feature, so it's weird that babel understands it in meteor but not in karma.  We'll have to try figure that out.  Possibly it will work when you fix the first issue, but I'm not too hopeful.

**Comment by mordrax** [comment]
@gadicc ok, gimme a sec, let me check!

**Comment by gadicc** [comment]
Great stuff, thanks for reporting back.

I'm glad you didn't need to modify your karma stuff, the idea is that these things should be compatible now.

Yes, `meteor update` will always get the latest released ecmascript-hot now!  And that's the latest stable release.  Next release is exciting also because of the speed improvements (you can check out the experimental release in the speed thread if you want it now).
