### ISSUE TITLE
Error when deploy with mupx

### ISSUE THREAD

**Issue by crapthings** [gadicc/meteor-react-hotloader#46]
cube-without-webpack git:(master) ✗ mupx logs --tail=50

	Meteor Up: Production Quality Meteor Deployments
	------------------------------------------------
	Configuration file : mup.json
	Settings file      : settings.json

	[139.162.2.61] npm WARN deprecated To upgrade to the latest stable version, run:
	[139.162.2.61] npm WARN deprecated
	[139.162.2.61] npm WARN deprecated   npm -g install npm@latest
	[139.162.2.61] npm WARN deprecated
	[139.162.2.61] npm WARN deprecated (Depending on how Node.js was installed on your system, you
	npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
	npm WARN deprecated on Windows, run them from an Administrator prompt.)
	npm WARN deprecated
	npm WARN deprecated If you're running the version of npm bundled with
	npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
	npm WARN deprecated will be bundled with a version of npm@2, which has some small
	npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
	npm WARN deprecated semver behavior.
	npm WARN package.json meteor-dev-bundle@0.0.0 No description
	npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
	[139.162.2.61] npm WARN package.json meteor-dev-bundle@0.0.0 No README data
	[139.162.2.61] => Starting meteor app on port:80
	[139.162.2.61] npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)

	/bundle/bundle/programs/server/node_modules/fibers/future.js:267
							throw(ex);
							      ^
	Error: Are you running inside a Meteor project dir?
	    at hot.lastHash (packages/gadicc_babel-compiler-hot/babelrc.js:45:1)
	    at packages/gadicc_babel-compiler-hot/babelrc.js:163:1
	    at packages/gadicc_babel-compiler-hot/babel-compiler.js:137:1
	[139.162.2.61]     at /bundle/bundle/programs/server/boot.js:283:10
	[139.162.2.61]     at Array.forEach (native)
	[139.162.2.61]     at Function._.each._.forEach (/bundle/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
	[139.162.2.61]     at /bundle/bundle/programs/server/boot.js:133:5
	npm WARN deprecated This version of npm lacks support for important features,
	npm WARN deprecated such as scoped packages, offered by the primary npm
	npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
	npm WARN deprecated latest stable version. To upgrade to npm@2, run:
	npm WARN deprecated
	npm WARN deprecated   npm -g install npm@latest-2
	npm WARN deprecated
	npm WARN deprecated To upgrade to the latest stable version, run:
	npm WARN deprecated
	npm WARN deprecated   npm -g install npm@latest
	npm WARN deprecated
	npm WARN deprecated (Depending on how Node.js was installed on your system, you
	npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
	npm WARN deprecated on Windows, run them from an Administrator prompt.)
	npm WARN deprecated
	npm WARN deprecated If you're running the version of npm bundled with
	npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
	npm WARN deprecated will be bundled with a version of npm@2, which has some small
	npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
	npm WARN deprecated semver behavior.

we droped webpack and move to native npm and using hot loader

meteor 1.3.2.2

**Comment by clayne11** [comment]
Are you using `gadicc:ecmascript-hot@1.3.2-fast.13`? If not, please try that and report back.

**Comment by crapthings** [comment]
[139.162.2.61] => Starting meteor app on port:80
[139.162.2.61] WARNING: npm peer requirements (for gadicc:ecmascript-hot) not installed:
[139.162.2.61]  - babel-preset-meteor@^6.6.7 not installed.
[139.162.2.61]
[139.162.2.61] Read more about installing npm peer dependencies:
[139.162.2.61]   http://guide.meteor.com/using-packages.html#peer-npm-dependencies

tried install  babel-preset-meteor but it still get this error

**Comment by gadicc** [comment]
Wait so the 1st error went away with an upgrade?

The 2nd error is safe to ignore, since we only use that package during build time, and not run time.  I'll add some code to silence this warning in the next version. I'll track in #50.

**Comment by crapthings** [comment]
but after this it reverts to old working one

**Comment by gadicc** [comment]
Wait so you're saying you're still getting `Error: Are you running inside a Meteor project dir?` ?

**Comment by crapthings** [comment]
i'm trying to deploy again, will post all mupx logs

**Comment by crapthings** [comment]
[139.162.2.61] /bundle/bundle/programs/server/node_modules/fibers/future.js:267
	[139.162.2.61] 						throw(ex);
	[139.162.2.61] 						      ^
	[139.162.2.61] TypeError: Cannot read property 'absolutePath' of undefined
	[139.162.2.61]     at WebApp.rawConnectHandlers.use.res.writeHead.content-type (packages/gadicc_modules-runtime-hot/modules-runtime-proxy.js:15:1)
	[139.162.2.61]     at /bundle/bundle/programs/server/boot.js:290:5
	[139.162.2.61] npm WARN deprecated This version of npm lacks support for important features,
	[139.162.2.61] npm WARN deprecated such as scoped packages, offered by the primary npm
	[139.162.2.61] npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
	[139.162.2.61] npm WARN deprecated latest stable version. To upgrade to npm@2, run:
	[139.162.2.61] npm WARN deprecated
	[139.162.2.61] => Starting meteor app on port:80
	reset models done
	fake users done
	fake groups done
	fake tags done
	fake docs done
	[139.162.2.61] npm WARN deprecated   npm -g install npm@latest-2
	npm WARN deprecated
	npm WARN deprecated To upgrade to the latest stable version, run:
	npm WARN deprecated
	npm WARN deprecated   npm -g install npm@latest
	npm WARN deprecated
	npm WARN deprecated (Depending on how Node.js was installed on your system, you
	npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
	npm WARN deprecated on Windows, run them from an Administrator prompt.)
	npm WARN deprecated
	npm WARN deprecated If you're running the version of npm bundled with
	npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
	npm WARN deprecated will be bundled with a version of npm@2, which has some small
	npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
	npm WARN deprecated semver behavior.
	npm WARN package.json meteor-dev-bundle@0.0.0 No description
	npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
	npm WARN package.json meteor-dev-bundle@0.0.0 No README data
	npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
	WARNING: npm peer requirements (for gadicc:ecmascript-hot) not installed:
	 - babel-preset-meteor@^6.6.7 not installed.

	Read more about installing npm peer dependencies:
	  http://guide.meteor.com/using-packages.html#peer-npm-dependencies

**Comment by gadicc** [comment]
Haha this seems like a "lucky packet" where every time you get a different error :)

We shouldn't really be running any of the 'modules-runtime-hot' code in production though, so I'll get this fixed in the next release.

**Comment by crapthings** [comment]
LoL

btw thanks all the great efforsts !!!

**Comment by gadicc** [comment]
@crapthings, sorry, this is fixed but it might be a while until this lands in a publishable release... I just finished a massive refactor, and things are quite different now.  but I hope to have a testing / experimental release out sometime this weekend.

**Comment by gadicc** [comment]
Here's the experimental release https://github.com/gadicc/meteor-react-hotloader/issues/51.  Will of course be in the next stable whenever that is.  And thanks for the kind words earlier! :)
